// Words everyone (except the imposter) sees. Concrete, easy to talk around.
module.exports = [
  'Pizza', 'Beach', 'Hospital', 'Guitar', 'Airport', 'Wedding', 'Library', 'Snow',
  'Coffee', 'Elephant', 'Football', 'Dentist', 'Rainbow', 'Castle', 'Submarine',
  'Birthday', 'Volcano', 'Toothbrush', 'Netflix', 'Gym', 'Desert', 'Ambulance',
  'Passport', 'Mirror', 'Pancakes', 'Zombie', 'Wallet', 'Camping', 'Barber',
  'Fireworks', 'Umbrella', 'Museum', 'Helicopter', 'Ice cream', 'Jungle',
  'Karaoke', 'Laundry', 'Marathon', 'Nightclub', 'Ocean', 'Piano', 'Pharmacy',
  'Restaurant', 'Sunglasses', 'Taxi', 'Vacuum', 'Waterfall', 'Yoga', 'Zoo',
  'Bakery', 'Circus', 'Detective', 'Earthquake', 'Farm', 'Ghost', 'Honeymoon',
  'Igloo', 'Jail', 'Kitchen', 'Lighthouse', 'Magnet', 'Nurse', 'Office',
  'Parachute', 'Queue', 'Roller coaster', 'Spider', 'Train station', 'Uniform',
  'Vampire', 'Windmill', 'Cinema', 'Basketball', 'Chocolate', 'Doctor',
  'Escalator', 'Firefighter', 'Garden', 'Haircut', 'Internet', 'Jacket',
  'Keyboard', 'Lemon', 'Mountain', 'Newspaper', 'Onion', 'Photographer',
  'Rainstorm', 'Sandwich', 'Teacher', 'Umbrella stand', 'Village', 'Whale',
  'Airbnb', 'Bus stop', 'Cactus', 'Dinosaur', 'Election', 'Funeral', 'Grandma',
  'Hotel', 'Instagram', 'Jetski', 'Kangaroo', 'Lottery', 'Museum guard',
  'Nightmare', 'Olympics', 'Picnic', 'Robot', 'Supermarket', 'Tattoo',
  'Uber', 'Violin', 'Wifi', 'Yacht', 'Alarm clock', 'Balloon', 'Casino',
  'Doorbell', 'Eyebrows', 'Fridge', 'Graveyard', 'Helmet', 'Injection',
  'Jigsaw puzzle', 'Ketchup', 'Ladder', 'Moustache', 'Nap', 'Oven',
  'Pillow fight', 'Quicksand', 'Rollerblades', 'Selfie', 'Toaster',
  'Underwear', 'Vending machine', 'Wheelchair', 'X-ray', 'Yoga mat',
  'Zipper', 'Bank robbery', 'Cruise ship', 'Dance battle', 'Escape room',
  'First date', 'Group chat', 'Haunted house', 'Job interview', 'Karate',
  'Long flight', 'Magic trick', 'New Year', 'Parking ticket', 'Road trip',
  'Ski slope', 'Traffic jam', 'Water park', 'Zoom call'
];
